[project]
name = "timeseries-autoencoder"
version = "v0.0.5"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "mlx>=0.30.1",
    "notebook>=7.5.1",
    "pandas>=2.3.3",
    "pydantic>=2.12.5",
    "scikit-learn>=1.8.0",
    "tensorboardx>=2.6.4",
    "tensorflow>=2.20.0",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "pandas-stubs>=2.3.3.251219",
    "ruff>=0.14.10",
    "types-requests>=2.32.4.20250913",
    "types-tensorflow>=2.18.0.20251008",
]
test = [
    "coverage>=7.13.0",
    "pytest>=9.0.2",
    "pytest-mock>=3.15.1",
]

[tool.pytest]
addopts = [
    "-v"
]
testpaths = [
    "tests",
]
pythonpath = [
    "src",
]

[tool.coverage.run]
source = [
    "src",
]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
]
ignore = [
    "E501",  # line too long, handled by black
    "B008",  # do not perform function calls in argument defaults
    "B006",  # do not use mutable data structures for argument defaults
    "B027",  # an empty method in an abstract base class, but has no abstract decorator
    "C901",  # too complex
    "W191",  # indentation contains tabs
]

[tool.mypy]
plugins = ["pydantic.mypy"]
strict = true
python_version = "3.12"
disable_error_code = ["import-untyped"]

[[tool.mypy.overrides]]
module = "mlx.*"
ignore_missing_imports = true
follow_imports = "skip"
